version: "3.7"
networks:
  redis-network:
    name: redis-cluster-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
services:
  redis-cluster:
    image: redis:6-alpine
    command: 'redis-cli --cluster create
    172.18.0.11:6379 172.18.0.12:6379 172.18.0.13:6379 172.18.0.14:6379
    172.18.0.15:6379 172.18.0.16:6379 172.18.0.17:6379 172.18.0.18:6379
    --cluster-yes --cluster-replicas 1'
    networks:
      - redis-network
    depends_on:
      - redis1
      - redis2
      - redis3
      - redis4
      - redis5
      - redis6
      - redis7
      - redis8
  redis1:
    image: redis:6-alpine
    container_name: redis1
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      redis-network:
        ipv4_address: 172.18.0.11
    expose:
      - 6379
    volumes:
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
  redis2:
    image: redis:6-alpine
    container_name: redis2
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      redis-network:
        ipv4_address: 172.18.0.12
    expose:
      - 6379
    volumes:
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
  redis3:
    image: redis:6-alpine
    container_name: redis3
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      redis-network:
        ipv4_address: 172.18.0.13
    expose:
      - 6379
    volumes:
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
  redis4:
    image: redis:6-alpine
    container_name: redis4
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      redis-network:
        ipv4_address: 172.18.0.14
    expose:
      - 6379
    volumes:
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
  redis5:
    image: redis:6-alpine
    container_name: redis5
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      redis-network:
        ipv4_address: 172.18.0.15
    expose:
      - 6379
    volumes:
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
  redis6:
    image: redis:6-alpine
    container_name: redis6
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      redis-network:
        ipv4_address: 172.18.0.16
    expose:
      - 6379
    volumes:
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
  redis7:
    image: redis:6-alpine
    container_name: redis7
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      redis-network:
        ipv4_address: 172.18.0.17
    expose:
      - 6379
    volumes:
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
  redis8:
    image: redis:6-alpine
    container_name: redis8
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      redis-network:
        ipv4_address: 172.18.0.18
    expose:
      - 6379
    volumes:
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf